//
//  UIColor+Extension.swift
//  CalendarApp
//
//  Created by ming xu on 11/29/24.
//

import UIKit

extension UIColor {

    // DO NOT EDIT THIS FILE

    static let calendarApp = CalendarApp()

    struct CalendarApp {
        let black = UIColor.black
        let offPink = UIColor(red: 255/255, green: 239/255, blue: 239/255, alpha: 1)
        let darkPink = UIColor(red: 255/255, green: 106/255, blue: 193/255, alpha: 1)
        let transpPink = UIColor(red: 255/255, green: 106/255, blue: 193/255, alpha: 0.57)
        let white = UIColor.white
        let green = UIColor(red: 186/255, green: 255/255, blue: 171/255, alpha: 1)
        let silver = UIColor(red: 191/255, green: 191/255, blue: 191/255, alpha: 1)
    }

}

